### ISSUE TITLE
Assure Immutability of nested reducers on MasterStore

### ISSUE THREAD

**Issue by jcperez-ch** [jcperez-ch/flaxs#2]
To assure immutability, we might need to leverage the use of Object.freeze every time we merge a new state.

We need to make sure as well that we can create nested namespaces like:

``` js
// user.js
flaxs.createReducer('user', (state, payload) => {}, { info: {}});
```

and

``` js
// userPreferences.js
flaxs.createReducer('user.preferences', (state, payload) => {}, { language: 'en', locale: 'en-CA' });
```

and at the end have a deep immutable state like:

``` json
{
    "user": {
        "info": {},
        "preferences": {
            "language": "en",
            "locale": "en-CA"
        }
    }
}
```

**Comment by tomzmtl** [comment]
I would also consider implementing a library like `Immutable.js` to make sure any data coming from the store cannot be altered.

**Comment by jcperez-ch** [comment]
Fixed in https://github.com/jcperez-ch/flaxs/pull/3
